### ISSUE TITLE
Authentication is done using Facebook/Twitter via Parse.

### ISSUE THREAD

**Issue by rafagcamargo** [TravelGuide/TravelGuide#16]

**Comment by kprav** [comment]
@rafagcamargo @SharedMocha Here are the steps to create a Facebook App and integrate it for login/authentication

First, please pull changes from master and have your branches in sync.

Facebook:
1. Goto Facebook, login to your account and create a new App (Go to https://developers.facebook.com/apps and click the "+ Add a New App" button & Select Android)
2. Give the App a Name - TravelGuide
     a. Is this a test versin of another app - No
     b. Category - Travel
3. Follow the steps sequentially after this
     a. Package Name - com.travelguide
     b. Default ACtivity Class Name - com.travelguide.activities.LoginActivity / com.travelguide.fragments.LoginFragment / com.travelguide.activities.TravelGuideActivity 
     c. Development Key Hashes - Execute following command
         On Windows:
           keytool -exportcert -alias androiddebugkey -keystore %HOMEPATH%.android\debug.keystore -storepass android -keypass -android | openssl sha1 -binary | openssl base64
         On Mac:
           keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore -storepass android -keypass -android | openssl sha1 -binary | openssl base64
     d. Release Key Hash - Leave Blank
4. Click the "MyApps" tab button on the Top of the screen and then click TravelGuide
5. Click Settings on the left side pane and choose the Basic tab.
6. Key Hashes - Enter the hash that was generated in step 3c.
7. Flip Single Sign On to "YES" and leave Depp Linking set to "NO"
8. Make a note of the App ID and App Secret visible at the top.
9. Click Save Changes

Parse:
1. Head over to Parse and select the TravelGuide App
2. Click the Settings tab at the top
3. Click Authentication on the left side pane.
4. Allow Facebook authentication must already be set to "Yes"
5. Click "+ Add Application" button and enter your App ID and App Secret noted in Step 7 above.

Android Studio:
1. Open strings.xml, find facebook_app_id and set your App ID here (from Step 7 above).
2. Don't check in strings.xml to github with this value. Each of us must use our own App ID.

Notes:
1. I commented the line ParseUser.enableAutomaticUser() in TravelGuideApplication.java as it was causing issues and interfering with Facebook login

**Comment by kprav** [comment]
@rafagcamargo @SharedMocha Feel free to close this issue once both of you have the integration working.
